
package detection.sensorsoap.sensors;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NewMessageInt", targetNamespace = "http://sensors.SensorSOAP.Detection/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewMessageInt {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://sensors.SensorSOAP.Detection/", className = "detection.sensorsoap.sensors.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://sensors.SensorSOAP.Detection/", className = "detection.sensorsoap.sensors.SendMessageResponse")
    @Action(input = "http://sensors.SensorSOAP.Detection/NewMessageInt/sendMessageRequest", output = "http://sensors.SensorSOAP.Detection/NewMessageInt/sendMessageResponse")
    public void sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        Event arg0);

}
