
package detection.sensorsoap.sensors;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NewMessageImplService", targetNamespace = "http://sensors.SensorSOAP.Detection/", wsdlLocation = "http://localhost:8000/NewMessageService?wsdl")
public class NewMessageImplService
    extends Service
{

    private final static URL NEWMESSAGEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NEWMESSAGEIMPLSERVICE_EXCEPTION;
    private final static QName NEWMESSAGEIMPLSERVICE_QNAME = new QName("http://sensors.SensorSOAP.Detection/", "NewMessageImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/NewMessageService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEWMESSAGEIMPLSERVICE_WSDL_LOCATION = url;
        NEWMESSAGEIMPLSERVICE_EXCEPTION = e;
    }

    public NewMessageImplService() {
        super(__getWsdlLocation(), NEWMESSAGEIMPLSERVICE_QNAME);
    }

    public NewMessageImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEWMESSAGEIMPLSERVICE_QNAME, features);
    }

    public NewMessageImplService(URL wsdlLocation) {
        super(wsdlLocation, NEWMESSAGEIMPLSERVICE_QNAME);
    }

    public NewMessageImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEWMESSAGEIMPLSERVICE_QNAME, features);
    }

    public NewMessageImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewMessageImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NewMessageInt
     */
    @WebEndpoint(name = "NewMessageImplPort")
    public NewMessageInt getNewMessageImplPort() {
        return super.getPort(new QName("http://sensors.SensorSOAP.Detection/", "NewMessageImplPort"), NewMessageInt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewMessageInt
     */
    @WebEndpoint(name = "NewMessageImplPort")
    public NewMessageInt getNewMessageImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sensors.SensorSOAP.Detection/", "NewMessageImplPort"), NewMessageInt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEWMESSAGEIMPLSERVICE_EXCEPTION!= null) {
            throw NEWMESSAGEIMPLSERVICE_EXCEPTION;
        }
        return NEWMESSAGEIMPLSERVICE_WSDL_LOCATION;
    }

}
